name: Update Packagist

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist update
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://packagist.org/api/update-package'
          method: 'POST'
          contentType: 'application/json'
          data: '{"username": "${{ secrets.PACKAGIST_USERNAME }}", "apiToken": "${{ secrets.PACKAGIST_TOKEN }}", "repository": {"url": "https://github.com/${{ github.repository }}"}}'