name: Update Packagist

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist update
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=scorninpc&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
            -d'{"repository":{"url":"https://github.com/${{ github.repository }}"}}'